<a href="https://colab.research.google.com/github/LalithaEvani/Madhumeha/blob/main/cardiovascular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset used
From January 2017 till June 2019, 1,357 subjects with T2DM were recruited in the study. Patients with T2DM were recruited from the Inpatient Department of Endocrinology in Lu He hospital

https://www.nature.com/articles/s41598-020-71321-2

AI model to determine the risk of T2DM patients to develop to CHD(Coronary Heart Disease), which has potential value in providing early warning personalized guidance of CHD risk for both T2DM patients and clinicians.

CHD is a disease of the less blood supplying to heart muscle vessels11 manifested as hyperlipidaemia, myocardial infarction, and angina pectoris

It is known that individuals’ basic information like gender and age, and blood test indexes such as blood pressure, total cholesterol (TC), low-density lipoprotein cholesterol (LDL-C), high-density lipoprotein cholesterol (HDL-C) as well as smoking behaviour, diabetes status can be considered as risk factors of causing CHD

AI (random forest) based model to predict the risk of developing CHD for individuals with T2DM

the predictive model achieved an AUC of 0.77 (fivefold cross-validation) in the training dataset and an AUC of 0.80 in the testing dataset, respectively. Moreover, the model achieved an AUC of 0.71 on a totally independent dataset including 1,253 newly recruited T2DM patients.

table containing range parameters for data considered 

https://www.nature.com/articles/s41598-020-71321-2/tables/1 

we use the information entropy function and Gini impurity function to check the information hidden in each feature. One feature will get a higher score if this series of data contain more information for classification and vice versa. The information entropy function-based feature selection method is implemented by using random forest model with 500 decision trees in sci-kit-learn 0.2228 in Python 3.

Webserver based prediction 

https://www.cuilab.cn/dchd/#single

In [1]:
# importing libraries
import numpy as np
import pandas as pd
import math
import random
import matplotlib.pyplot as plt

In [2]:
gender1= np.random.choice([0,1], size=7610, p=[0.482,0.518]) #0 for female 
gender2 = np.random.choice([0,1], size=2390, p=[0.470,0.530]) 
gender = np.concatenate((gender1,gender2))
gender

array([0, 1, 1, ..., 1, 0, 0])

In [3]:
smokers1= np.random.choice([1,0], size=7610, p=[0.381,0.619])
smokers2= np.random.choice([1,0], size=2390, p=[0.424,0.576])
smokers = np.concatenate((smokers1,smokers2))
print(smokers)


[1 1 1 ... 0 1 0]


In [4]:
drinking_alcohol1= np.random.choice([1,0], size=7610, p=[0.318,0.682])
drinking_alcohol2= np.random.choice([1,0], size=2390, p=[0.319,0.681])
drinking_alcohol = np.concatenate((drinking_alcohol1,drinking_alcohol2))
print(drinking_alcohol)

[0 0 0 ... 0 0 1]


In [5]:
age1 = np.random.uniform(39.77,68.37,7610)
age2 = np.random.uniform(55.16,74.66,2390)
age = np.concatenate((age1,age2))
age

array([48.65409493, 55.32903093, 40.46534301, ..., 72.67267925,
       69.25982765, 59.22768047])

In [6]:
course_of_hypertension1 = np.random.uniform(4.92,5.98,7610)
course_of_hypertension2 = np.random.uniform(9.10,11.55,2390)
course_of_hypertension = np.concatenate((course_of_hypertension1, course_of_hypertension2))
course_of_hypertension

array([ 5.03003977,  4.97103505,  5.84149114, ...,  9.31662244,
       10.29675842,  9.38969826])

In [7]:
course_of_diabetes1 = np.random.uniform(6.80,7.73,7610)
course_of_diabetes2= np.random.uniform(10.38,12.36,2390)
course_of_diabetes = np.concatenate((course_of_diabetes1,course_of_diabetes2))
course_of_diabetes

array([ 7.01627555,  7.68631188,  7.29596759, ..., 10.55542634,
       10.8526894 , 10.79582999])

In [8]:
systolic_pressure1 = np.random.uniform(110.26,147.74,7610)
systolic_pressure2= np.random.uniform(107.74,149.62,2390)
systolic_pressure = np.concatenate((systolic_pressure1,systolic_pressure2))
systolic_pressure

array([117.27626877, 140.99115342, 113.76417658, ..., 111.03501437,
       125.32371643, 125.25477433])

In [9]:
diastolic_pressure1 = np.random.uniform(65.5, 88.72,7610)
diastolic_pressure2 = np.random.uniform(60.1,85.5,2390)
diastolic_pressure = np.concatenate((diastolic_pressure1,diastolic_pressure2))
diastolic_pressure

array([80.76391602, 67.8714535 , 69.02254392, ..., 73.23630918,
       76.36741162, 71.04711378])

In [10]:
heartrate1 = np.random.uniform(70.45,96.39,7610)
heartrate2 = np.random.uniform(65.81,88.07,2390)
heartrate = np.concatenate((heartrate1,heartrate2))
heartrate

array([81.3124868 , 82.19390373, 94.35266412, ..., 76.99341672,
       69.78484016, 68.33685872])

In [11]:
body_mass_index1 = np.random.uniform(22.08,30.16,7610)
body_mass_index2 = np.random.uniform(22.66,30.01,2390)
body_mass_index = np.concatenate((body_mass_index1,body_mass_index2))
body_mass_index

array([25.54148108, 29.20095534, 22.83167507, ..., 25.01055181,
       26.06523807, 23.73538042])

In [12]:
waist_hip_rate1 = np.random.uniform(0.87,1.01,7610)
waist_hip_rate2 = np.random.uniform(0.88,1.02,2390)
waist_hip_rate = np.concatenate((waist_hip_rate1,waist_hip_rate2))
waist_hip_rate

array([0.97552264, 0.97266335, 0.95746041, ..., 0.92798664, 0.89646777,
       0.95606217])

In [13]:
blood_platelet1 = np.random.uniform(156.47,294.29,7610)
blood_platelet2 = np.random.uniform(112.42,287.86,2390)
blood_platelet = np.concatenate((blood_platelet1,blood_platelet2))
blood_platelet

array([184.9402072 , 178.31483497, 157.79819899, ..., 165.03836987,
       140.81163586, 203.76818759])

In [14]:
hemoglobin1 = np.random.uniform(7.56,12.12,7610)
hemoglobin2 = np.random.uniform(7.18,11.58,2390)
hemoglobin = np.concatenate((hemoglobin1,hemoglobin2))
hemoglobin

array([7.95433277, 8.55787328, 8.05794992, ..., 7.54570396, 9.45159464,
       7.47947924])

In [15]:
serum_creatinine1 = np.random.uniform(39.59,94.91,7610)
serum_creatinine2 = np.random.uniform(44.24,108.18,2390)
serum_creatinine = np.concatenate((serum_creatinine1,serum_creatinine2))
serum_creatinine

array([48.76283419, 44.47575163, 44.44625579, ..., 71.02132076,
       92.62022914, 47.9796293 ])

In [16]:
uric_acid1 = np.random.uniform(312.95,326.53,7610)
uric_acid2 = np.random.uniform(321.41,346.41,2390)
uric_acid = np.concatenate((uric_acid1,uric_acid2))
uric_acid

array([320.09802498, 314.52319106, 322.05229482, ..., 332.58820781,
       323.6948931 , 332.58518416])

In [17]:
serum_triglyceride1 = np.random.uniform(1.88,2.17,7610)
serum_triglyceride2 = np.random.uniform(1.58,1.95,2390)
serum_triglyceride = np.concatenate((serum_triglyceride1,serum_triglyceride2))
serum_triglyceride

array([1.90959059, 2.06273524, 1.94189494, ..., 1.70840961, 1.88856274,
       1.64909184])

In [39]:
total_cholesterol1 = np.random.uniform(3.5,5.92,7610)
total_cholesterol2 = np.random.uniform(2.96,5.3,2390)
total_cholesterol = np.concatenate((total_cholesterol1,total_cholesterol2))
total_cholesterol

array([3.50798187, 5.38250631, 5.13017157, ..., 3.20890895, 5.10134072,
       5.0744999 ])

In [19]:
LDL_cholesterol1 = np.random.uniform(2.14,3.9,7610)
LDL_cholesterol2 = np.random.uniform(1.7,3.44,2390)
LDL_cholesterol = np.concatenate((LDL_cholesterol1,LDL_cholesterol2))
LDL_cholesterol

array([3.53224865, 2.2096279 , 3.4020882 , ..., 3.38762702, 3.39564501,
       3.00339123])

In [20]:
HDL_cholesterol1 = np.random.uniform(0.81,1.35,7610)
HDL_cholesterol2 = np.random.uniform(0.76,1.32,2390)
HDL_cholesterol = np.concatenate((HDL_cholesterol1,HDL_cholesterol2))
HDL_cholesterol

array([0.87335039, 1.08424007, 0.97579473, ..., 1.14454344, 0.95298909,
       0.79217   ])

In [21]:
fasting_blood_glucose1 = np.random.uniform(8.78,9.38,7610)
fasting_blood_glucose2 = np.random.uniform(8.15,9.08,2390)
fasting_blood_glucose = np.concatenate((fasting_blood_glucose1,fasting_blood_glucose2))
fasting_blood_glucose

array([8.78376658, 9.13339349, 9.32109778, ..., 9.04166872, 8.63631275,
       9.01975021])

In [22]:
insulin0h1 = np.random.uniform(14.26,21.60,7610)
insulin0h2 = np.random.uniform(18.98,40.30,2390)
insulin0h = np.concatenate((insulin0h1,insulin0h2))
insulin0h

array([17.73345507, 15.56021853, 17.42388267, ..., 28.78670866,
       37.49023723, 34.88093643])

In [23]:
insulin1h1 = np.random.uniform(53.64,64.38,7610)
insulin1h2 = np.random.uniform(64.38,93.06,2390)
insulin1h = np.concatenate((insulin1h1,insulin1h2))
insulin1h

array([56.79156721, 63.1182038 , 61.84869667, ..., 68.02124017,
       90.09601892, 69.37156899])

In [24]:
insulin2h1 = np.random.uniform(59.82,70.36,7610)
insulin2h2 = np.random.uniform(69.47,100.19,2390)
insulin2h = np.concatenate((insulin2h1,insulin2h2))
insulin2h

array([62.26578257, 63.600528  , 66.66264949, ..., 89.75799477,
       95.36830646, 72.96804692])

In [25]:
insulin3h1 = np.random.uniform(48.16,58.52,7610)
insulin3h2 = np.random.uniform(60.06,90.87,2390)
insulin3h = np.concatenate((insulin3h1,insulin3h2))
insulin3h

array([56.99751344, 51.17287151, 52.95553544, ..., 86.7196416 ,
       72.93958238, 73.80939547])

In [26]:
cpeptide0h1 = np.random.uniform(1.51,1.64,7610)
cpeptide0h2 = np.random.uniform(1.68,1.95,2390)
cpeptide0h = np.concatenate((cpeptide0h1,cpeptide0h2))
cpeptide0h 

array([1.55035155, 1.61557117, 1.57729505, ..., 1.72679268, 1.76408293,
       1.82071779])

In [27]:
cpeptide1h1 = np.random.uniform(2.63,2.88,7610)
cpeptide1h2 = np.random.uniform(2.62,3.01,2390)
cpeptide1h = np.concatenate((cpeptide1h1,cpeptide1h2))
cpeptide1h

array([2.66214914, 2.86929938, 2.63938839, ..., 2.69948147, 2.99978278,
       2.76346031])

In [28]:
cpeptide2h1 = np.random.uniform(3.94,4.33,7610)
cpeptide2h2 = np.random.uniform(3.84,4.48,2390)
cpeptide2h = np.concatenate((cpeptide2h1,cpeptide2h2))
cpeptide2h

array([3.97149181, 3.97657482, 4.16157706, ..., 4.15828047, 3.88178538,
       4.34544857])

In [29]:
cpeptide3h1 = np.random.uniform(4.05,4.44,7610)
cpeptide3h2 = np.random.uniform(4.14,4.86,2390)
cpeptide3h = np.concatenate((cpeptide3h1,cpeptide3h2))
cpeptide3h

array([4.26975522, 4.42160004, 4.11931401, ..., 4.34861165, 4.63307136,
       4.76157217])

In [30]:

label1 = np.array([0 for i in range(7610)])
label2 = np.array([1 for i in range(2390)])
label = np.concatenate((label1,label2))
label


array([0, 0, 0, ..., 1, 1, 1])

In [31]:
data = pd.DataFrame()

# defining the columns of the dataset
data['gender'] = gender
data['smokers'] = smokers
data['drinking alcohol'] = drinking_alcohol
data['age'] = age
data['course of hypertension'] = course_of_hypertension
data['course of diabetes'] = course_of_diabetes
data['systolic pressure'] = systolic_pressure
data['diastolic pressure'] = diastolic_pressure
data['heartrate'] = heartrate
data['body mass index'] = body_mass_index
data['waist hip rate'] = waist_hip_rate
data['blood platelet'] = blood_platelet
data['hemoglobin'] = hemoglobin
data['serum creatinine'] = serum_creatinine
data['uric acid'] = uric_acid
data['serum triglyceride'] = serum_triglyceride
data['total cholesterol'] = total_cholesterol
data['LDL cholesterol'] = LDL_cholesterol
data['HDL cholesterol'] = HDL_cholesterol
data['fasting blood glucose'] = fasting_blood_glucose
data['insulin 0 h'] = insulin0h
data['insulin 1 h'] = insulin1h
data['insulin 2 h'] = insulin2h
data['insulin 3 h'] = insulin3h
data['c-peptide 0 h'] = cpeptide0h
data['c-peptide 1 h'] = cpeptide1h
data['c-peptide 2 h'] = cpeptide2h
data['c-peptide 3 h'] = cpeptide3h
data['label'] = label

data

gender  smokers  drinking alcohol        age  course of hypertension  \
0          0        1                 0  48.654095                5.030040   
1          1        1                 0  55.329031                4.971035   
2          1        1                 0  40.465343                5.841491   
3          1        1                 1  42.002881                5.018067   
4          0        0                 1  57.992213                5.652927   
...      ...      ...               ...        ...                     ...   
9995       1        0                 0  63.923591               10.588691   
9996       0        0                 0  62.501890                9.641847   
9997       1        0                 0  72.672679                9.316622   
9998       0        1                 0  69.259828               10.296758   
9999       0        0                 1  59.227680                9.389698   

      course of diabetes  systolic pressure  diastolic pressure  heartrate  \
0               7.016276         117.276269           80.763916  81.312487   
1               7.686312         140.991153           67.871453  82.193904   
2               7.295968         113.764177           69.022544  94.352664   
3               7.474600         136.011204           74.219569  70.822251   
4               7.564002         145.228945           85.457356  89.618183   
...                  ...                ...                 ...        ...   
9995           11.055659         145.922098           69.603052  72.641065   
9996           11.213081         144.010698           78.497338  78.601933   
9997           10.555426         111.035014           73.236309  76.993417   
9998           10.852689         125.323716           76.367412  69.784840   
9999           10.795830         125.254774           71.047114  68.336859   

      body mass index  ...  fasting blood glucose  insulin 0 h  insulin 1 h  \
0           25.541481  ...               8.783767    17.733455    56.791567   
1           29.200955  ...               9.133393    15.560219    63.118204   
2           22.831675  ...               9.321098    17.423883    61.848697   
3           22.896307  ...               8.814333    15.866851    58.604254   
4           29.693761  ...               9.030606    14.509467    61.343153   
...               ...  ...                    ...          ...          ...   
9995        26.182690  ...               8.583274    21.303602    69.540262   
9996        25.369006  ...               8.982185    23.967063    81.018621   
9997        25.010552  ...               9.041669    28.786709    68.021240   
9998        26.065238  ...               8.636313    37.490237    90.096019   
9999        23.735380  ...               9.019750    34.880936    69.371569   

      insulin 2 h  insulin 3 h  c-peptide 0 h  c-peptide 1 h  c-peptide 2 h  \
0       62.265783    56.997513       1.550352       2.662149       3.971492   
1       63.600528    51.172872       1.615571       2.869299       3.976575   
2       66.662649    52.955535       1.577295       2.639388       4.161577   
3       63.655445    51.638842       1.529334       2.673309       4.238613   
4       66.262061    49.085819       1.561491       2.654616       4.110975   
...           ...          ...            ...            ...            ...   
9995    77.647696    86.803652       1.787934       2.646685       4.062610   
9996    86.423009    63.883113       1.907145       2.907221       3.973844   
9997    89.757995    86.719642       1.726793       2.699481       4.158280   
9998    95.368306    72.939582       1.764083       2.999783       3.881785   
9999    72.968047    73.809395       1.820718       2.763460       4.345449   

      c-peptide 3 h  label  
0          4.269755      0  
1          4.421600      0  
2          4.119314      0  
3          4.064006      0  
4          4.437058      0  
...             ...    ...  
9995       4.148671      1  
99

In [32]:
cardio_data = data.sample(frac=1)
cardio_data.reset_index(inplace= True, drop = True)
cardio_data

gender  smokers  drinking alcohol        age  course of hypertension  \
0          0        1                 1  65.851196               10.596679   
1          1        0                 0  58.529134                9.413841   
2          0        1                 0  62.579016               11.004075   
3          0        0                 1  62.039286                5.842525   
4          1        0                 1  48.174831                5.443777   
...      ...      ...               ...        ...                     ...   
9995       1        0                 0  60.042127                5.369463   
9996       1        1                 1  46.351860                5.772669   
9997       0        0                 0  59.135601                5.566585   
9998       1        0                 0  55.605649                5.490611   
9999       1        0                 1  43.156587                4.996065   

      course of diabetes  systolic pressure  diastolic pressure  heartrate  \
0              10.933069         115.635494           79.034143  75.183610   
1              10.384116         120.177974           73.825864  84.391013   
2              11.853374         140.128415           74.490801  66.749773   
3               7.330177         123.987420           87.934653  78.906013   
4               7.389364         130.841985           82.840085  84.263473   
...                  ...                ...                 ...        ...   
9995            7.604061         143.464866           66.808899  86.336804   
9996            7.342041         115.943897           70.791847  87.691533   
9997            6.956371         116.424117           73.081330  93.398248   
9998            7.654876         140.441120           82.083860  75.931349   
9999            7.204685         138.757880           82.386542  72.717855   

      body mass index  ...  fasting blood glucose  insulin 0 h  insulin 1 h  \
0           28.780193  ...               8.336309    36.398548    86.675861   
1           22.892935  ...               8.816701    34.967749    73.947348   
2           24.432276  ...               8.352254    24.762380    73.001599   
3           22.795450  ...               8.924394    15.646501    57.703124   
4           28.063707  ...               8.841761    16.293955    64.233952   
...               ...  ...                    ...          ...          ...   
9995        25.604164  ...               9.359454    17.446553    60.359903   
9996        22.935119  ...               9.213388    20.952370    56.917510   
9997        28.399058  ...               9.376674    20.203430    57.797796   
9998        29.947927  ...               9.281812    20.580281    62.237532   
9999        27.046939  ...               9.066644    17.854968    61.084537   

      insulin 2 h  insulin 3 h  c-peptide 0 h  c-peptide 1 h  c-peptide 2 h  \
0       71.390342    60.812020       1.784685       2.748416       4.454146   
1       78.458938    81.779302       1.713179       2.970240       3.872234   
2       93.532904    65.568413       1.815071       2.765215       3.988513   
3       61.889550    53.808904       1.610529       2.833245       4.094328   
4       67.750660    53.808036       1.513928       2.777120       4.154340   
...           ...          ...            ...            ...            ...   
9995    65.409926    53.098768       1.625103       2.820857       4.214344   
9996    63.214319    52.261992       1.521084       2.763870       4.001559   
9997    63.034819    48.372381       1.627789       2.671630       4.180419   
9998    60.990899    50.377625       1.634907       2.672647       4.180058   
9999    63.215717    53.477395       1.544996       2.801195       4.271492   

      c-peptide 3 h  label  
0          4.757872      1  
1          4.573412      1  
2          4.738059      1  
3          4.343682      0  
4          4.164358      0  
...             ...    ...  
9995       4.434133      0  
99

In [33]:
cardio_data.to_csv('cardiovascular.csv')

In [34]:
import pandas as pd
cardio = pd.read_csv('/content/cardiovascular.csv')

In [35]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [36]:
cardio_validate = pd.read_csv('/content/drive/MyDrive/cardiovascular.csv')

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

cardio_data = pd.DataFrame(cardio ,columns=cardio.columns[:-1])
cardio_label = cardio.label
X_train, X_test, y_train, y_test = train_test_split(cardio_data, cardio_label, test_size = 0.30, random_state = 17) 

clf = RandomForestClassifier(max_depth=10, random_state=0)
clf.fit(X_train, y_train)

#Training Error in terms of points:
from sklearn.metrics import accuracy_score
print("{:.2f} % of the testing points classified correctly".format(100*accuracy_score(clf.predict(X_test), y_test)))

cardio_validate_data = pd.DataFrame(cardio_validate,columns = cardio_validate.columns[:-1])
cardio_validate_label = cardio_validate.label
print("accuracy of validation",100*accuracy_score(clf.predict(cardio_validate_data),cardio_validate_label))

100.00 % of the testing points classified correctly
accuracy of validation 100.0
